name: Build macOS

on:
  push:
  pull_request:

jobs:
  tests-macos:
    name: Tests
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        php:
          - '7.4'
          - '8.0'
          - '8.1'
    continue-on-error: ${{ matrix.php == '8.1' }}
    defaults:
      run:
        shell: bash
    env:
      PHP_VERSION: ${{ matrix.php }}
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install llvm
        shell: bash
        run: |
          brew update
          brew install llvm

      - name: Install PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: ffi, pcntl

      - name: Get composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer cache directory
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: |
          composer update --prefer-dist --prefer-stable --no-interaction -vvv

      - name: Run tests
        run: |
          composer test-init
          composer test

      - name: Stop kafka
        run: |
          kafka-server-stop;
          zookeeper-server-stop;